name: cross_share
version: 1.0.0
homepage: https://github.com/marchdev-tk/cross_share
description: Share files and URLs on both Mobile (Android/iOS), Web and Desktop (Windows, macOS, Linux).

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  meta: ^1.1.8
  esys_flutter_share: ^1.0.2
  url_launcher: ^5.4.2
  url_launcher_web: ^0.1.1+1
  url_launcher_macos: 0.0.1+4
  url_launcher_fde:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/flutter_plugins/url_launcher_fde

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
