name: cross_share
version: 1.0.1
homepage: https://github.com/marchdev-tk/cross_share
description: Share files and URLs on both Mobile (Android/iOS), Web and Desktop (Windows, macOS, Linux).

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  meta: ^1.1.8
  esys_flutter_share: ^1.0.2
  url_launcher: ^6.0.2
  url_launcher_web: ^2.0.0
  url_launcher_macos: ^2.0.0
  url_launcher_windows: ^2.0.0
  url_launcher_linux: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
